### ISSUE TITLE
Internal parts of the multiprocessing module contain socket passing

### ISSUE THREAD

**Issue by dholth** [carljm/wsgiwatcher#4]
FYI there is cross-platform inter-process socket passing code in multiprocessing; it has to pickle sockets to communicate with its worker processes. On BSD & newer Linux it would probably be fine to just always open the socket with SO_REUSEPORT, but on Windows passing the socket may be able to accomplish the same thing (two or more processes accepting connections on the same listening address).

**Comment by davisagli** [comment]
Generally the WSGI server is responsible for opening its own sockets, so that's not under our control.

**Comment by carljm** [comment]
Yeah. ReloadWSGI could provide a socket because it only works with wsgiref servers. WSGIWatcher operates at a higher abstraction level (our API is "give us a callable that runs some arbitrary server" - actually even the WSGI in the name is misleading, as I don't think anything in WSGIWatcher even assumes WSGI).

**Comment by dholth** [comment]
Yes, unfortunately this kind of feature would require specialization per supported server.
