### ISSUE TITLE
define what needs to happen for a release

### ISSUE THREAD

**Issue by mmerickel** [carljm/wsgiwatcher#6]
Is there a plan to release and maintain this project? If so, what can be done to help? If not, should we fork this and release it ourselves? I'm trying to determine a path forward to having Pyramid's `pserve` depend on this as a library in the future.

**Comment by carljm** [comment]
I'm not sure that I can commit to being a proper maintainer for this project -- I wrote it as a kind of proof of concept at the PyCon sprints last year and haven't touched it since, and don't have an immediate need for it myself. I'm happy for it to be useful to Pyramid, and equally happy for the Pylons project to just wholesale adopt it if you plan to use it :-) I've added you as a repo collaborator; I'm quite open to just having this repo moved over to github.com/pylons if you like.

**Comment by mmerickel** [comment]
Hey @carljm I just wanted to give an update that I've released a very heavily modified version of this library under a new project named hupper [1]. What you do with the wsgiwatcher repo is up to you now. Thanks for showing me this repo at Pycon!

[1] https://github.com/Pylons/hupper

**Comment by carljm** [comment]
Thanks for the update, and for taking this and running with it! For now I'll make this repo's description point to hupper; in the future if it seems clear that there's no longer anything here that interests anyone, I'll just delete the repo and turn it into a redirect.
